version: '2'
services:
  postgresql:
    image: postgres:11.4
    container_name: postgres-questrya
    network_mode: bridge
    restart: unless-stopped
    ports:
      - 5432:5432/tcp
    environment:
      - POSTGRES_USER=postgres
      - PGPASSWORD=postgres
      - POSTGRES_DB=questrya
      - TZ=Etc/UTC
  rabbitmq:
    image: rabbitmq:3.7-management
    container_name: rabbitmq-questrya
    network_mode: bridge
    restart: unless-stopped
    ports:
      - 15672:15672
      - 15671:15671
      - 5672:5672
      - 5671:5671
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
